global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Windows/Mac // linux에서는 IP 주소를 따로 설정해야 함.
        labels:
          application: "salang-backend"
